### ISSUE TITLE
Use container or similar

### ISSUE THREAD

**Issue by davidsowerby** [KrailOrg/krail-testApp#19]
Deployment of the war for testing is clumsy, and hardwired to a locally installed Tomcat.  Running in a container may be better

**Comment by mcollovati** [comment]
Links to some available gradle plugins

https://github.com/chrisgahlert/gradle-dcompose-plugin
https://github.com/bmuschko/gradle-docker-plugin

**Comment by mcollovati** [comment]
Created branch `ISSUE-19/tests-on-docker-containers` with configuration for testing on top of docker containers. 
To run tests there are now two gradle tasks: `integrationTestTomcat7` or `integrationTestTomcat8`.

Test does not work for me on develop branch (because of services and push problems) but runs fine on a separated local branch with workarounds applied

**Comment by mcollovati** [comment]
I think so; for Vert.x container there is already issue #39.

**Comment by davidsowerby** [comment]
Closed
